### ISSUE TITLE
Values for certain fields are missing for AoE2:DE

### ISSUE THREAD

**Issue by Divy1211** [Tapsa/AGE#18]
AoE2:DE supports additional values for the following fields:

Unit Attributes (For effect commands modifying attributes, 26-34, 59-77, 100-115):
https://ugc.aoe2.rocks/general/attributes/attributes/

Player Resources (For effect commands modifying player resources, 250-284):
https://ugc.aoe2.rocks/general/resources/resources/

Additional Command Types for effects (8, 9, 18, 19, 28, 29, 30-39, 40-49):
https://ageofempires.fandom.com/wiki/Genie_Editor#Commands

Tech Modifiers in command types 8, 18, 28, 38, and 48:
https://ageofempires.fandom.com/wiki/Genie_Editor#Technology

Unit Task Types:
https://ageofempires.fandom.com/wiki/Genie_Editor#Tasks

Unit Resource Store Mode (32):
Value `32`: Used by (Elite) konniks to prevent pop from decreasing during its dying animation

Unit Hide in Editor (2):
Value `2`: Show in others Tab

**Comment by bingbingwangyyds** [comment]
I have updated a new Chinese AGE and fixed all the mistakes above and add much more new infomation about DE.It is all unique to release to public,if someone have interesting about it and want to translate it into English or other languages,you can contact me on Github,I will provide materials about it to help you,it is my pleasure,thank you.

**Comment by Tapsa** [comment]
I have addressed some of these in https://github.com/Tapsa/AGE/releases/tag/2024.5.2
My time is limited and I have no plans for when I can add the rest.

**Comment by Divy1211** [comment]
> I have addressed some of these in https://github.com/Tapsa/AGE/releases/tag/2024.5.2 My time is limited and I have no plans for when I can add the rest.

No worries, thanks for the new release!

**Comment by Tapsa** [comment]
I have added the rest of the mentioned things in https://github.com/Tapsa/AGE/releases/tag/2024.5.9

**Comment by Divy1211** [comment]
Thanks for the update <3 . With this, I believe A.G.E. has all the lists updated with known DE functionality.

Just a quick note: Additional Command Types for effects (9, 19, 29,39, 49) were missed
